sudo: required
services:
  - docker

before_install:
  - docker build -t fletcher1991/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fletcher1991/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-eu-west-1-891123523376"
  bucket_path: "docker-react"
  on:
    branch: main 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY